-- ============================================================
-- LEMON AI — MEMBER 1 DATABASE TABLES
-- Run this in Supabase SQL Editor BEFORE starting the app
-- ============================================================

-- ============================================================
-- COMPETITOR RESEARCH TABLE
-- Stores every AI market research run per user
-- ============================================================
CREATE TABLE IF NOT EXISTS competitor_researches (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         TEXT NOT NULL,
  niche           TEXT NOT NULL,
  target_audience TEXT,
  country         TEXT DEFAULT 'IN',
  competitor_urls TEXT[] DEFAULT '{}',
  research_data   JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE competitor_researches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS competitor_researches_policy ON competitor_researches;
CREATE POLICY competitor_researches_policy ON competitor_researches
  FOR ALL USING (user_id = requesting_user_id())
  WITH CHECK (user_id = requesting_user_id());

CREATE INDEX IF NOT EXISTS idx_competitor_researches_user ON competitor_researches(user_id, created_at DESC);

-- ============================================================
-- STUDIO CONTENT DRAFTS TABLE
-- Stores Reels, Carousels, Blogs, Ad Creatives generated by AI
-- ============================================================
CREATE TABLE IF NOT EXISTS studio_drafts (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      TEXT NOT NULL,
  type         TEXT NOT NULL CHECK (type IN ('REEL', 'CAROUSEL', 'BLOG', 'AD_CREATIVE', 'STRATEGY')),
  title        TEXT,
  content_data JSONB NOT NULL DEFAULT '{}',
  status       TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'saved', 'scheduled')),
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE studio_drafts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS studio_drafts_policy ON studio_drafts;
CREATE POLICY studio_drafts_policy ON studio_drafts
  FOR ALL USING (user_id = requesting_user_id())
  WITH CHECK (user_id = requesting_user_id());

CREATE INDEX IF NOT EXISTS idx_studio_drafts_user_type ON studio_drafts(user_id, type, created_at DESC);
