"use client";

import { useState, useEffect, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import {
  Calendar as CalendarIcon,
  Sparkles,
  Clock,
  Send,
  CheckCircle2,
  AlertCircle,
  ImageIcon,
  Check,
  Globe,
  Video,
  Play,
  Download,
  Film,
  LayoutGrid,
  ChevronLeft,
  ChevronRight,
  RefreshCw,
  FileText,
} from "lucide-react";
import ChannelAvatar from "@/components/channel-avatar";
import { ChannelTypeEnum } from "@/constants/channels";
import Link from "next/link";
import { cn } from "@/lib/utils";

interface ScheduleFromResearchDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  mode?: "single" | "batch";
  initialTopic?: string;
  initialContent?: string;
  initialImages?: { url: string }[];
  initialVideoUrl?: string;
  initialCarouselSlides?: any[];
  suggestedFormat?: string;
  researchContext?: {
    niche: string;
    businessName?: string;
    targetAudience?: string;
    competitors?: string;
    hashtags?: string[];
    strategyPillars?: any[];
    strategySchedule?: any[];
  };
}

export default function ScheduleFromResearchDialog({
  open,
  onOpenChange,
  mode = "single",
  initialTopic = "",
  initialContent = "",
  initialImages = [],
  initialVideoUrl = "",
  initialCarouselSlides = [],
  suggestedFormat = "FEED_POST",
  researchContext,
}: ScheduleFromResearchDialogProps) {
  const queryClient = useQueryClient();
  
  // Content states
  const [topic, setTopic] = useState(initialTopic);
  const [generatedContent, setGeneratedContent] = useState(initialContent);
  const [generatedImages, setGeneratedImages] = useState<{ url: string }[]>(initialImages);
  const [videoUrl, setVideoUrl] = useState<string>(initialVideoUrl);
  const [carouselSlides, setCarouselSlides] = useState<any[]>(initialCarouselSlides);
  const [activeSlideIdx, setActiveSlideIdx] = useState(0);

  // Settings states
  const [selectedChannelIds, setSelectedChannelIds] = useState<string[]>([]);
  const [includeImage, setIncludeImage] = useState(true);
  const [publishStatus, setPublishStatus] = useState<"queue" | "draft">("queue");
  const [activeMediaTab, setActiveMediaTab] = useState<"preview" | "script">("preview");

  const [scheduledDate, setScheduledDate] = useState<string>(() => {
    const d = new Date();
    d.setHours(d.getHours() + 2);
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    const hours = String(d.getHours()).padStart(2, "0");
    const minutes = String(d.getMinutes()).padStart(2, "0");
    return `${year}-${month}-${day}T${hours}:${minutes}`;
  });

  const hasAutoGeneratedRef = useRef(false);

  // Fetch channels
  const { data: channelsData, isLoading: isLoadingChannels } = useQuery({
    queryKey: ["channels"],
    queryFn: async () => {
      const res = await fetch("/api/channel");
      if (!res.ok) throw new Error("Failed to load channels");
      return res.json();
    },
    enabled: open,
  });

  const allChannels = channelsData?.channels || [];
  const connectedChannels = allChannels.filter((c: any) => c.connected);
  const availableChannels = connectedChannels.length > 0 ? connectedChannels : allChannels;

  // Auto-select first available channels
  useEffect(() => {
    if (availableChannels.length > 0 && selectedChannelIds.length === 0) {
      const defaultIds = connectedChannels.length > 0
        ? connectedChannels.map((c: any) => c.id || c.channel_type_id || c.type)
        : [availableChannels[0]?.id || availableChannels[0]?.type || "default"];
      setSelectedChannelIds(defaultIds);
    }
  }, [availableChannels, connectedChannels, selectedChannelIds.length]);

  // AI Single Post Generator Mutation
  const { mutateAsync: runAIGeneration, isPending: isGenerating } = useMutation({
    mutationFn: async (overrideTopic?: string) => {
      const promptTarget = overrideTopic || topic;
      if (!promptTarget.trim()) return null;

      const isReel = suggestedFormat === "REEL";
      const isCarousel = suggestedFormat === "CAROUSEL";

      const promptText = `Write a high-engaging social media post based on this winning trending hook/angle: "${promptTarget}".
Niche: ${researchContext?.niche || "General"}. Target Audience: ${researchContext?.targetAudience || "Target customers"}.
Format: ${suggestedFormat}.
${isReel ? "Include visual director cues, 3-second hook, high-retention body, and CTA." : ""}
${isCarousel ? "Include a 5-slide carousel breakdown outline." : ""}
Include 3-5 relevant viral hashtags: ${researchContext?.hashtags?.slice(0, 5).join(" ") || ""}`;

      const res = await fetch("/api/post/generate-post", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "generate",
          prompt: promptText,
          generateImage: includeImage && !isReel,
          channelId: selectedChannelIds[0] || undefined,
        }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Failed to generate post");
      }
      return res.json();
    },
    onSuccess: (data) => {
      if (!data) return;
      if (data.content) setGeneratedContent(data.content);
      if (data.images && data.images.length > 0) {
        setGeneratedImages(data.images);
      }
      toast.success("AI generated full post copy & visuals!");
    },
    onError: (err: any) => {
      toast.error(err.message || "Could not generate post content");
    },
  });

  // Automatically trigger AI generation on mount if not already populated with initial content
  useEffect(() => {
    if (open) {
      if (initialContent) {
        setGeneratedContent(initialContent);
      }
      if (initialImages && initialImages.length > 0) {
        setGeneratedImages(initialImages);
      }
      if (initialVideoUrl) {
        setVideoUrl(initialVideoUrl);
      }
      if (initialCarouselSlides && initialCarouselSlides.length > 0) {
        setCarouselSlides(initialCarouselSlides);
      }
      if (initialTopic) {
        setTopic(initialTopic);
      }

      // If no pre-existing content was passed and we have a topic, auto-generate immediately
      if (!initialContent && initialTopic && !hasAutoGeneratedRef.current) {
        hasAutoGeneratedRef.current = true;
        runAIGeneration(initialTopic).catch(() => {});
      }
    } else {
      hasAutoGeneratedRef.current = false;
    }
  }, [open, initialContent, initialImages, initialVideoUrl, initialCarouselSlides, initialTopic]);

  const toggleChannelSelection = (id: string) => {
    setSelectedChannelIds((prev) => {
      if (prev.includes(id)) {
        if (prev.length === 1) return prev;
        return prev.filter((item) => item !== id);
      } else {
        return [...prev, id];
      }
    });
  };

  const handleSelectAllChannels = () => {
    if (selectedChannelIds.length === availableChannels.length) {
      setSelectedChannelIds([availableChannels[0]?.id || availableChannels[0]?.type || "default"]);
    } else {
      setSelectedChannelIds(availableChannels.map((c: any) => c.id || c.channel_type_id || c.type));
    }
  };

  const setQuickTime = (hoursFromNow: number) => {
    const d = new Date();
    d.setHours(d.getHours() + hoursFromNow);
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    const hours = String(d.getHours()).padStart(2, "0");
    const minutes = String(d.getMinutes()).padStart(2, "0");
    setScheduledDate(`${year}-${month}-${day}T${hours}:${minutes}`);
  };

  // Single Post Schedule Mutation
  const { mutate: scheduleSinglePost, isPending: isScheduling } = useMutation({
    mutationFn: async () => {
      let finalContent = generatedContent.trim();
      let finalImages = generatedImages;

      // If content is still empty, generate right now
      if (!finalContent) {
        const generated = await runAIGeneration(undefined);
        if (generated?.content) {
          finalContent = generated.content;
          if (generated.images) finalImages = generated.images;
        } else {
          finalContent = topic.trim();
        }
      }

      if (!finalContent) {
        throw new Error("Please write or generate post content first.");
      }

      const targetChannels = selectedChannelIds.length > 0
        ? selectedChannelIds
        : [availableChannels[0]?.id || undefined];

      const postPayload = {
        posts: targetChannels.map((channelId) => ({
          channelTypeId: channelId,
          content: finalContent,
          images: finalImages,
        })),
        scheduledAt: new Date(scheduledDate).toISOString(),
        status: publishStatus,
      };

      const res = await fetch("/api/post", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(postPayload),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Failed to schedule post");
      }
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["posts"] });
      queryClient.invalidateQueries({ queryKey: ["scheduled-posts"] });
      queryClient.invalidateQueries({ queryKey: ["calendar-posts"] });
      toast.success(
        `Post successfully ${publishStatus === "draft" ? "saved to draft" : "scheduled to calendar"} across ${selectedChannelIds.length} channel(s)!`
      );
      onOpenChange(false);
    },
    onError: (err: any) => {
      toast.error(err.message || "Failed to schedule post");
    },
  });

  const isReel = suggestedFormat === "REEL" || Boolean(videoUrl);
  const isCarousel = suggestedFormat === "CAROUSEL" || (carouselSlides && carouselSlides.length > 0);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center justify-between pr-4">
            <DialogTitle className="flex items-center gap-2 text-lg">
              {isReel ? (
                <>
                  <Video className="size-5 text-blue-500" />
                  Schedule Video Reel to Social Media
                </>
              ) : isCarousel ? (
                <>
                  <LayoutGrid className="size-5 text-purple-500" />
                  Schedule Carousel Deck
                </>
              ) : (
                <>
                  <Sparkles className="size-5 text-primary" />
                  Schedule Post from Trending Hook
                </>
              )}
            </DialogTitle>
            <Badge variant="outline" className="text-xs font-semibold uppercase">
              {suggestedFormat}
            </Badge>
          </div>
          <DialogDescription>
            Preview your generated media, select your social channels, and schedule for automated publishing.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {/* 1. Destination Social Channels */}
          <div className="space-y-2 p-3 rounded-xl border bg-muted/20">
            <div className="flex items-center justify-between">
              <Label className="text-xs font-semibold text-foreground flex items-center gap-1.5">
                <Globe className="size-3.5 text-primary" /> 1. Select Target Social Channels
              </Label>
              {availableChannels.length > 1 && (
                <button
                  type="button"
                  onClick={handleSelectAllChannels}
                  className="text-xs text-primary font-medium hover:underline cursor-pointer"
                >
                  {selectedChannelIds.length === availableChannels.length ? "Deselect All" : "Select All"}
                </button>
              )}
            </div>

            {availableChannels.length === 0 && !isLoadingChannels ? (
              <p className="text-xs text-muted-foreground">
                No channels found. Will schedule as general draft in your social calendar.
              </p>
            ) : (
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {availableChannels.map((c: any) => {
                  const chKey = c.id || c.channel_type_id || c.type || "default";
                  const isSelected = selectedChannelIds.includes(chKey);
                  const channelType = (c.type as ChannelTypeEnum) || ChannelTypeEnum.TWITTER;

                  return (
                    <div
                      key={chKey}
                      onClick={() => toggleChannelSelection(chKey)}
                      className={cn(
                        "flex items-center justify-between p-2 rounded-xl border transition-all cursor-pointer select-none",
                        isSelected
                          ? "bg-card border-primary/50 shadow-xs ring-1 ring-primary/30"
                          : "bg-muted/10 hover:bg-muted/30 border-border/70 opacity-60"
                      )}
                    >
                      <div className="flex items-center gap-2 min-w-0 pr-1">
                        <ChannelAvatar
                          type={channelType}
                          color={c.color || "#000000"}
                          profileImage={c.profile_image}
                          name={c.name || c.type}
                          size="sm"
                        />
                        <div className="min-w-0">
                          <p className="text-xs font-semibold text-foreground truncate">
                            {c.name || c.type}
                          </p>
                          <p className="text-[10px] text-muted-foreground truncate">
                            {c.connected ? (c.handle || "Connected") : "Calendar Draft"}
                          </p>
                        </div>
                      </div>
                      <div
                        className={cn(
                          "size-4 rounded-md border flex items-center justify-center shrink-0 transition-colors",
                          isSelected
                            ? "bg-primary border-primary text-primary-foreground"
                            : "border-muted-foreground/40 bg-background"
                        )}
                      >
                        {isSelected && <Check className="size-3" />}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* 2. Schedule Date & Time */}
          <div className="space-y-2 p-3 rounded-xl border bg-muted/20">
            <div className="flex items-center justify-between">
              <Label htmlFor="post-datetime" className="text-xs font-semibold flex items-center gap-1.5">
                <Clock className="size-3.5 text-primary" /> 2. Schedule Date & Time
              </Label>
              <div className="flex items-center gap-1.5 text-[11px]">
                <button
                  type="button"
                  onClick={() => setQuickTime(1)}
                  className="px-2 py-0.5 rounded-md bg-background border hover:bg-muted font-medium text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                >
                  +1 hr
                </button>
                <button
                  type="button"
                  onClick={() => setQuickTime(3)}
                  className="px-2 py-0.5 rounded-md bg-background border hover:bg-muted font-medium text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                >
                  +3 hrs
                </button>
                <button
                  type="button"
                  onClick={() => setQuickTime(24)}
                  className="px-2 py-0.5 rounded-md bg-background border hover:bg-muted font-medium text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                >
                  Tomorrow
                </button>
              </div>
            </div>
            <Input
              id="post-datetime"
              type="datetime-local"
              value={scheduledDate}
              onChange={(e) => setScheduledDate(e.target.value)}
              className="text-xs font-medium h-9"
            />
          </div>

          {/* 3. Auto-Publish & Visual Toggles */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            <div className="p-3 rounded-xl border bg-card flex items-center justify-between">
              <div className="space-y-0.5 pr-2">
                <Label htmlFor="post-status-toggle" className="text-xs font-semibold flex items-center gap-1.5 cursor-pointer">
                  <Send className="size-3.5 text-primary" /> Auto-Publish to Live Feeds
                </Label>
                <p className="text-[10px] text-muted-foreground">
                  {publishStatus === "queue" ? "Queue for auto-publish" : "Save as draft"}
                </p>
              </div>
              <Switch
                id="post-status-toggle"
                checked={publishStatus === "queue"}
                onCheckedChange={(checked) => setPublishStatus(checked ? "queue" : "draft")}
              />
            </div>

            <div className="p-3 rounded-xl border bg-card flex items-center justify-between">
              <div className="space-y-0.5 pr-2">
                <Label htmlFor="image-gen-toggle" className="text-xs font-semibold flex items-center gap-1.5 cursor-pointer">
                  <ImageIcon className="size-3.5 text-primary" /> Auto-Include AI Creative
                </Label>
                <p className="text-[10px] text-muted-foreground">
                  Generate matching visual asset
                </p>
              </div>
              <Switch
                id="image-gen-toggle"
                checked={includeImage}
                onCheckedChange={setIncludeImage}
              />
            </div>
          </div>

          {/* 4. Interactive Media Player / Playable Video Condition */}
          {isReel && (
            <div className="p-3.5 rounded-xl bg-muted/20 border space-y-3">
              <div className="flex items-center justify-between border-b pb-2">
                <div className="flex items-center gap-1.5">
                  <Badge className="bg-blue-500/15 text-blue-600 dark:text-blue-400 border-blue-300 text-xs font-semibold">
                    <Video className="size-3 mr-1" /> 9:16 Vertical Reel Player
                  </Badge>
                  <span className="text-xs text-muted-foreground font-medium">Ready for Instagram, YouTube Shorts & Facebook Reels</span>
                </div>
                {videoUrl && (
                  <Button size="sm" variant="outline" asChild className="h-7 text-xs font-semibold gap-1 px-2">
                    <a href={videoUrl} download="reel.mp4" target="_blank" rel="noopener noreferrer">
                      <Download className="size-3" /> Download MP4
                    </a>
                  </Button>
                )}
              </div>

              <div className="flex flex-col sm:flex-row items-center gap-4">
                <div className="relative w-[150px] aspect-[9/16] rounded-xl overflow-hidden shadow-md border border-primary/30 bg-black shrink-0">
                  {videoUrl ? (
                    <video
                      src={videoUrl}
                      controls
                      autoPlay
                      loop
                      muted
                      playsInline
                      className="w-full h-full object-cover"
                    />
                  ) : generatedImages.length > 0 ? (
                    <img
                      src={generatedImages[0].url}
                      alt="Reel Cover"
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="w-full h-full flex flex-col items-center justify-center text-center p-3 text-white/70">
                      <Play className="size-8 mb-1 text-primary animate-pulse" />
                      <span className="text-[10px] font-semibold">Vertical Video Reel</span>
                    </div>
                  )}
                </div>

                <div className="space-y-2 text-xs flex-1">
                  <div className="space-y-1">
                    <p className="font-semibold text-foreground">Playable Commercial Reel Script</p>
                    <p className="text-[11px] text-muted-foreground leading-relaxed">
                      AI structured this reel with a 3-second retention pattern interrupt, emotional agitation, and a high-converting call to action.
                    </p>
                  </div>
                  <div className="p-2 rounded-lg bg-background border text-[11px] font-mono text-muted-foreground max-h-24 overflow-y-auto">
                    {topic || "Retention Hook Scene Attached"}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Carousel Slide Deck Viewer */}
          {isCarousel && carouselSlides.length > 0 && (
            <div className="p-3.5 rounded-xl border bg-card shadow-xs space-y-3">
              <div className="flex items-center justify-between border-b pb-2">
                <Badge className="bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-300 text-xs font-semibold">
                  <LayoutGrid className="size-3 mr-1" /> Carousel Slide Deck ({carouselSlides.length} Slides)
                </Badge>
                <span className="text-xs text-muted-foreground font-mono">
                  Slide {activeSlideIdx + 1} of {carouselSlides.length}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-muted/30 border min-h-[120px] flex flex-col justify-between space-y-2">
                <div>
                  <p className="text-xs font-bold text-foreground">
                    {carouselSlides[activeSlideIdx]?.headline || `Slide ${activeSlideIdx + 1}`}
                  </p>
                  <p className="text-[11px] text-muted-foreground mt-1">
                    {carouselSlides[activeSlideIdx]?.subtext || carouselSlides[activeSlideIdx]?.body}
                  </p>
                </div>
                <div className="pt-2 border-t flex items-center justify-between text-[10px] text-muted-foreground">
                  <span>Swipe Direction</span>
                  <span className="text-primary font-semibold">
                    {carouselSlides[activeSlideIdx]?.swipePrompt || "Next →"}
                  </span>
                </div>
              </div>

              <div className="flex items-center justify-between pt-1">
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 px-2.5 text-xs"
                  onClick={() => setActiveSlideIdx((prev) => Math.max(0, prev - 1))}
                  disabled={activeSlideIdx === 0}
                >
                  <ChevronLeft className="size-3.5 mr-1" /> Prev Slide
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 px-2.5 text-xs"
                  onClick={() => setActiveSlideIdx((prev) => Math.min(carouselSlides.length - 1, prev + 1))}
                  disabled={activeSlideIdx === carouselSlides.length - 1}
                >
                  Next Slide <ChevronRight className="size-3.5 ml-1" />
                </Button>
              </div>
            </div>
          )}

          {/* 5. Post Content (Auto-Generated & Editable) */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="post-content" className="text-xs font-semibold flex items-center gap-1.5">
                <FileText className="size-3.5 text-primary" /> Post Copy & Hashtags (Editable)
              </Label>
              <Button
                type="button"
                size="sm"
                variant="ghost"
                className="h-7 text-xs font-medium text-primary gap-1 px-2"
                onClick={() => runAIGeneration(undefined)}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <>
                    <Sparkles className="size-3 animate-spin" /> AI Generating...
                  </>
                ) : (
                  <>
                    <RefreshCw className="size-3" /> Regenerate Copy
                  </>
                )}
              </Button>
            </div>

            {isGenerating && !generatedContent ? (
              <div className="p-6 rounded-xl border border-primary/30 bg-primary/5 text-center space-y-2">
                <Sparkles className="size-5 animate-spin text-primary mx-auto" />
                <p className="text-xs font-semibold text-primary">
                  AI is crafting high-converting post copy & visuals...
                </p>
                <p className="text-[11px] text-muted-foreground">
                  Analyzing tone, audience psychology, and viral hashtags
                </p>
              </div>
            ) : (
              <Textarea
                id="post-content"
                rows={5}
                value={generatedContent}
                onChange={(e) => setGeneratedContent(e.target.value)}
                placeholder="Post copy..."
                className="text-xs font-sans leading-relaxed"
              />
            )}

            {!isReel && generatedImages.length > 0 && (
              <div className="mt-2">
                <Label className="text-[11px] text-muted-foreground block mb-1">
                  Attached Visual Asset
                </Label>
                <div className="relative w-28 h-28 rounded-lg overflow-hidden border">
                  <img
                    src={generatedImages[0].url}
                    alt="Creative"
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
            )}
          </div>
        </div>

        <DialogFooter className="gap-2 sm:gap-0 pt-2 border-t">
          <Button variant="ghost" size="sm" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>

          <Button
            type="button"
            size="sm"
            onClick={() => scheduleSinglePost()}
            disabled={isScheduling || isGenerating}
            className="font-semibold gap-1.5 px-5 bg-primary text-primary-foreground hover:bg-primary/90 shadow-sm"
          >
            {isScheduling ? (
              <>
                <Clock className="size-3.5 animate-spin" /> Scheduling...
              </>
            ) : (
              <>
                <CalendarIcon className="size-3.5" /> Schedule to Calendar
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
